2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_setup.py:_flush():67] Configure stats pid to 2002402
2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/.config/wandb/settings
2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_setup.py:_flush():67] Loading settings from /speech/utkarsh/da6401_assignment1/wandb/settings
2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250303_174908-nm4pitce/logs/debug.log
2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /speech/utkarsh/da6401_assignment1/wandb/run-20250303_174908-nm4pitce/logs/debug-internal.log
2025-03-03 17:49:08,272 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():761] calling init triggers
2025-03-03 17:49:08,273 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():766] wandb.init called with sweep_config: {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 32, 'hidden_layers_count': 5, 'learning_rate': 0.0001, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
config: {'_wandb': {}}
2025-03-03 17:49:08,273 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():784] starting backend
2025-03-03 17:49:08,273 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():788] sending inform_init request
2025-03-03 17:49:08,274 INFO    Thread-5 (_run_job):2002402 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-03 17:49:08,274 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():803] backend started and connected
2025-03-03 17:49:08,275 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_config_callback():1261] config_cb None None {'activation': 'relu', 'batch_size': 16, 'epochs': 10, 'hidden_layer_size': 32, 'hidden_layers_count': 5, 'learning_rate': 0.0001, 'optimizer': 'momentum', 'weight_decay': 0, 'weight_init': 'random'}
2025-03-03 17:49:08,276 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():896] updated telemetry
2025-03-03 17:49:08,282 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-03 17:49:08,730 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():995] starting run threads in backend
2025-03-03 17:49:08,825 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_console_start():2377] atexit reg
2025-03-03 17:49:08,825 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-03 17:49:08,827 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-03 17:49:08,827 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-03 17:49:08,827 INFO    Thread-5 (_run_job):2002402 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-03 17:49:09,205 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_finish():2112] finishing run da24s011-indian-institute-of-technology-madras/neural-network-fashion-mnist/nm4pitce
2025-03-03 17:49:09,206 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_atexit_cleanup():2342] got exitcode: 1
2025-03-03 17:49:09,206 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_restore():2324] restore
2025-03-03 17:49:09,206 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_restore():2330] restore done
2025-03-03 17:49:11,439 WARNING MsgRouterThr:2002402 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/speech/utkarsh/miniconda3/envs/valle/lib/python3.10/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-03 17:49:11,440 INFO    MsgRouterThr:2002402 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-03 17:49:11,440 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_footer_history_summary_info():3958] rendering history
2025-03-03 17:49:11,440 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_footer_history_summary_info():3990] rendering summary
2025-03-03 17:49:11,441 INFO    Thread-5 (_run_job):2002402 [wandb_run.py:_footer_sync_info():3919] logging synced files
